version: '3.3'

services:
   db:
     container_name: wp-db
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./db_data:/docker-entrypoint-initdb.d
     restart: always
     env_file: .env
     ports: 
      - "33060:3306"

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     env_file: .env
     environment:
       WORDPRESS_DB_HOST: "db:3306"
     volumes:
       - .:/var/www/html
     
   phpmyadmin:
    container_name: wp-pma
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - /sessions
    env_file: .env

volumes:
    db_data: {}